using System.Diagnostics; using System.Windows; using System.Windows.Controls; using System.Windows.Input; using System.Windows.Media; using System.Windows.Media.Imaging; using System.Windows.Shapes; using Celeris.Client.Configuration; using Celeris.Client.Models; using Celeris.Client.Navigation; using Celeris.Client.Sessions; using Celeris.Client.Tabs; using Microsoft.Win32; using Microsoft.Web.WebView2.Core; using Microsoft.Web.WebView2.Wpf;
namespace Celeris.Client;
public partial class MainWindow : Window
{
 private bool _isFullScreen; private WindowState _restoreWindowState; private WindowStyle _restoreWindowStyle;
 private static readonly Uri ResearchHome = new("https://www.google.com/"); private readonly ClientSettings _settings; private readonly Uri _home; private readonly NavigationPolicy _policy; private readonly SessionManager _sessions = new(); private readonly TabManager _tabs = new(); private readonly Dictionary<Guid, WebView2> _views = []; private readonly string _data = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Celeris", "WebView2");
 public MainWindow(ClientSettings settings) { _settings = settings; _home = new(settings.BaseUrl); _policy = new(settings.AllowedOrigins); InitializeComponent(); ApplySystemTheme(); BuildLogo(); DataContext = _tabs; foreach (var f in settings.Favorites) { var b = new Button { Content = CreateFavoriteContent(f), Tag = f, ToolTip = f.Name }; b.Click += Favorite_Click; FavoritesPanel.Children.Add(b); } Loaded += async (_, _) => await CreateSessionAsync(); }
 private void ApplySystemTheme() => ApplyTheme((Registry.GetValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "AppsUseLightTheme", 1) as int? ?? 1) != 0);
 private void ApplyTheme(bool light) { Resources["AppBackground"] = Brush(light ? "#F3F7FA" : "#101827"); Resources["SurfaceBrush"] = Brush(light ? "#FFFFFF" : "#172033"); Resources["TextBrush"] = Brush(light ? "#263244" : "#E5E7EB"); Resources["MutedBrush"] = Brush(light ? "#64748B" : "#9CA3AF"); Resources["LineBrush"] = Brush(light ? "#D8E2EB" : "#263244"); Resources["PrimarySoftBrush"] = Brush(light ? "#DDEFFC" : "#293D52"); }
 private static SolidColorBrush Brush(string value) => new((Color)ColorConverter.ConvertFromString(value));
 private void BuildLogo() { var file = System.IO.Path.Combine(AppContext.BaseDirectory, "Assets", "logo.png"); if (System.IO.File.Exists(file)) LogoHost.Child = new Image { Source = new BitmapImage(new Uri(file)), Stretch = Stretch.Uniform, HorizontalAlignment = HorizontalAlignment.Left }; else LogoHost.Child = new TextBlock { Text = "CELERIS", Foreground = (Brush)FindResource("PrimaryBrush"), FontWeight = FontWeights.Bold, FontSize = 18, VerticalAlignment = VerticalAlignment.Center }; }
 private static UIElement CreateFavoriteContent(FavoriteItem f) { var panel = new StackPanel { Orientation = Orientation.Horizontal }; if (!string.IsNullOrWhiteSpace(f.IconPath)) panel.Children.Add(new Path { Data = Geometry.Parse(f.IconPath), Stroke = Brush("#74BDF0"), StrokeThickness = 1.8, StrokeLineJoin = PenLineJoin.Round, Width = 18, Height = 18, Stretch = Stretch.Uniform, Margin = new Thickness(0, 0, 7, 0) }); panel.Children.Add(new TextBlock { Text = f.Name, VerticalAlignment = VerticalAlignment.Center }); return panel; }
 private async Task CreateSessionAsync() => await CreateTabAsync(_sessions.CreateSession(), _home);
 private async Task CreateTabAsync(BrowserSession session, Uri uri, bool research = false, int? insertIndex = null)
 {
  var tab = _tabs.CreateTab(session, uri, research, insertIndex); if (research) tab.Title = "Pesquisa"; var view = new WebView2 { CreationProperties = new CoreWebView2CreationProperties { UserDataFolder = _data, ProfileName = session.ProfileName } }; _views[tab.Id] = view; Tabs.SelectedItem = tab; Show(tab);
  try { await view.EnsureCoreWebView2Async(); view.CoreWebView2.Settings.AreDevToolsEnabled = _settings.Browser.EnableDevTools; view.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled = false; view.CoreWebView2.DocumentTitleChanged += (_, _) => tab.Title = string.IsNullOrWhiteSpace(view.CoreWebView2.DocumentTitle) ? "Celeris" : view.CoreWebView2.DocumentTitle; view.CoreWebView2.SourceChanged += (_, _) => { if (Uri.TryCreate(view.Source?.ToString(), UriKind.Absolute, out var current)) { tab.CurrentUrl = current; if (ReferenceEquals(Current, tab)) AddressText.Text = current.AbsoluteUri; } }; view.CoreWebView2.HistoryChanged += (_, _) => { if (ReferenceEquals(Current, tab)) UpdateNavigationButtons(); }; view.CoreWebView2.NavigationStarting += (_, e) => HandleNavigation(tab, e.Uri, () => e.Cancel = true); view.CoreWebView2.NewWindowRequested += (_, e) => { e.Handled = true; if (tab.AllowExternalNavigation && Uri.TryCreate(e.Uri, UriKind.Absolute, out var popup)) view.Source = popup; else HandleNavigation(tab, e.Uri, () => { }); }; view.Source = uri; }
  catch (WebView2RuntimeNotFoundException) { ShowError("Microsoft WebView2 Runtime não está instalado."); } catch (Exception ex) { ShowError($"Não foi possível inicializar o conteúdo.\n{ex.Message}"); }
 }
 private void HandleNavigation(BrowserTab tab, string address, Action cancel) { if (!Uri.TryCreate(address, UriKind.Absolute, out var uri) || _policy.IsInternal(uri) || tab.AllowExternalNavigation && uri.Scheme is "http" or "https") return; cancel(); if (uri.Scheme is "http" or "https") Process.Start(new ProcessStartInfo(uri.AbsoluteUri) { UseShellExecute = true }); }
 private BrowserTab? Current => Tabs.SelectedItem as BrowserTab; private void Show(BrowserTab? tab) { BrowserHost.Children.Clear(); if (tab is not null && _views.TryGetValue(tab.Id, out var view)) BrowserHost.Children.Add(view); AddressText.Text = tab?.CurrentUrl.AbsoluteUri ?? ""; UpdateNavigationButtons(); } private void ShowError(string message) { BrowserHost.Children.Clear(); BrowserHost.Children.Add(new TextBlock { Text = message, TextAlignment = TextAlignment.Center, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Center, Foreground = (Brush)FindResource("TextBrush") }); }
 private void UpdateNavigationButtons() { var core = Current is { } tab && _views.TryGetValue(tab.Id, out var view) ? view.CoreWebView2 : null; BackButton.Visibility = core?.CanGoBack == true ? Visibility.Visible : Visibility.Collapsed; ForwardButton.Visibility = core?.CanGoForward == true ? Visibility.Visible : Visibility.Collapsed; }
 private void Back_Click(object s, RoutedEventArgs e) { if (Current is { } tab && _views.TryGetValue(tab.Id, out var view) && view.CanGoBack) view.GoBack(); }
 private void Forward_Click(object s, RoutedEventArgs e) { if (Current is { } tab && _views.TryGetValue(tab.Id, out var view) && view.CanGoForward) view.GoForward(); }
 private async void Research_Click(object s, RoutedEventArgs e) { var existing = _tabs.Tabs.FirstOrDefault(tab => tab.AllowExternalNavigation && SameAddress(tab.CurrentUrl, ResearchHome)); if (existing is not null) { Tabs.SelectedItem = existing; return; } var session = Current?.Session ?? _sessions.CreateSession(); await CreateTabAsync(session, ResearchHome, true); } private static bool SameAddress(Uri left, Uri right) => Uri.Compare(left, right, UriComponents.SchemeAndServer | UriComponents.Path, UriFormat.Unescaped, StringComparison.OrdinalIgnoreCase) == 0; private async void NewTab_Click(object s, RoutedEventArgs e) { if (Current is { } tab) await CreateTabAsync(tab.Session, _home); else await CreateSessionAsync(); } private async void NewSession_Click(object s, RoutedEventArgs e) => await CreateSessionAsync(); private void Home_Click(object s, RoutedEventArgs e) { if (Current is { } tab && _views.TryGetValue(tab.Id, out var view)) view.Source = _home; } private void Favorite_Click(object s, RoutedEventArgs e) { if (s is Button { Tag: FavoriteItem f } && Current is { } tab && _views.TryGetValue(tab.Id, out var view)) view.Source = f.Resolve(_home); } private void Tabs_SelectionChanged(object s, SelectionChangedEventArgs e) => Show(Current);
 private void CloseTab_Click(object s, RoutedEventArgs e) { e.Handled = true; if (s is not Button { Tag: BrowserTab tab }) return; var i = _tabs.Tabs.IndexOf(tab); _tabs.CloseTab(tab); if (_views.Remove(tab.Id, out var view)) view.Dispose(); if (_tabs.Tabs.Count == 0) Close(); else Tabs.SelectedIndex = Math.Min(i, _tabs.Tabs.Count - 1); }
 private void Options_Click(object s, RoutedEventArgs e) { if (OptionsButton.ContextMenu is { } menu) { menu.PlacementTarget = OptionsButton; menu.IsOpen = true; } }
 private void CopyAddress_Click(object s, RoutedEventArgs e) { if (Current is { } tab) Clipboard.SetText(tab.CurrentUrl.AbsoluteUri); }
 private void ToggleAddress_Click(object s, RoutedEventArgs e) { var show = AddressBar.Visibility != Visibility.Visible; AddressBar.Visibility = show ? Visibility.Visible : Visibility.Collapsed; ToggleAddressMenuItem.Header = show ? "Ocultar endereço" : "Exibir endereço"; AddressText.Text = Current?.CurrentUrl.AbsoluteUri ?? ""; }
 private void AddressText_KeyDown(object s, KeyEventArgs e) { if (e.Key != Key.Enter || Current is not { } tab || !_views.TryGetValue(tab.Id, out var view)) return; var value = AddressText.Text.Trim(); if (!value.Contains("://", StringComparison.Ordinal)) value = "https://" + value; if (Uri.TryCreate(value, UriKind.Absolute, out var destination) && destination.Scheme is "http" or "https") { view.Source = destination; Keyboard.ClearFocus(); } else MessageBox.Show("Informe um endereço HTTP ou HTTPS válido.", "Endereço inválido", MessageBoxButton.OK, MessageBoxImage.Warning); e.Handled = true; }
 private void Reload_Click(object s, RoutedEventArgs e) { if (Current is { } tab && _views.TryGetValue(tab.Id, out var view)) view.Reload(); }
 private void TabScroller_MouseWheel(object s, MouseWheelEventArgs e) { TabScroller.ScrollToHorizontalOffset(TabScroller.HorizontalOffset - e.Delta); e.Handled = true; }
 private async void DuplicateTab_Click(object s, RoutedEventArgs e) { if (s is not MenuItem { Tag: BrowserTab source }) return; var index = _tabs.Tabs.IndexOf(source); await CreateTabAsync(source.Session, source.CurrentUrl, source.AllowExternalNavigation, index + 1); }
 private void ToggleFullScreen_Click(object s, RoutedEventArgs e) { if (!_isFullScreen) { _restoreWindowState = WindowState; _restoreWindowStyle = WindowStyle; WindowStyle = WindowStyle.None; WindowState = WindowState.Maximized; _isFullScreen = true; } else ExitFullScreen(); }
 private void ExitFullScreen() { if (!_isFullScreen) return; WindowStyle = _restoreWindowStyle; WindowState = _restoreWindowState; _isFullScreen = false; }
 private void SystemTheme_Click(object s, RoutedEventArgs e) => ApplySystemTheme(); private void LightTheme_Click(object s, RoutedEventArgs e) => ApplyTheme(true); private void DarkTheme_Click(object s, RoutedEventArgs e) => ApplyTheme(false);
 private async void OnKeyDown(object s, KeyEventArgs e) { if (e.Key == Key.Escape && _isFullScreen) { ExitFullScreen(); e.Handled = true; } else if (Keyboard.Modifiers == ModifierKeys.Control && e.Key == Key.T) { NewTab_Click(s, e); e.Handled = true; } else if (Keyboard.Modifiers == (ModifierKeys.Control | ModifierKeys.Shift) && e.Key == Key.N) { await CreateSessionAsync(); e.Handled = true; } else if (Keyboard.Modifiers == ModifierKeys.Control && e.Key == Key.W && Current is { } tab) CloseTab_Click(new Button { Tag = tab }, e); else if (Keyboard.Modifiers == ModifierKeys.Alt && e.Key == Key.Home) Home_Click(s, e); }
 protected override void OnClosed(EventArgs e) { foreach (var view in _views.Values) view.Dispose(); base.OnClosed(e); }
}
